# Generated by Django 2.1.7 on 2019-04-13 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InterestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(default='static/images/groups/thumbnails/default_thumbnail.jpg', upload_to='static/images/groups/thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('value', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='static/images/profile_pictures/None/no-img.jpg', upload_to='static/images/profile_pictures/')),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('4th Year', '4th Year'), ('Grad', 'Graduate Student'), ('Alumni', 'Alumni')], max_length=50)),
                ('bio', models.TextField(max_length=500)),
                ('groups', models.ManyToManyField(to='interest_groups.InterestGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('grouppost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interest_groups.GroupPost')),
            ],
            options={
                'abstract': False,
            },
            bases=('interest_groups.grouppost',),
        ),
        migrations.CreateModel(
            name='DiscussionPost',
            fields=[
                ('grouppost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interest_groups.GroupPost')),
                ('title', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('interest_groups.grouppost',),
        ),
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('grouppost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='interest_groups.GroupPost')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('event_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('interest_groups.grouppost',),
        ),
        migrations.AddField(
            model_name='profile',
            name='posts',
            field=models.ManyToManyField(to='interest_groups.GroupPost'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interest_groups.GroupPost'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interest_groups.Profile'),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interest_groups.Profile'),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='interest_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interest_groups.InterestGroup'),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='interest_groups.GroupPost'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
        migrations.AddField(
            model_name='eventpost',
            name='attending',
            field=models.ManyToManyField(to='interest_groups.Profile'),
        ),
    ]
