# Generated by Django 2.1.7 on 2019-04-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='static/images/profile_pictures/default_profile_picture.jpg', upload_to='static/images/profile_pictures/'),
        ),
    ]
