# Generated by Django 2.1.7 on 2019-04-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_groups', '0002_auto_20190413_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='tagline',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
