# Generated by Django 2.1.6 on 2019-04-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_groups', '0003_auto_20190413_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='images/profile_pictures/default_profile_picture.jpg', upload_to='images/profile_pictures/'),
        ),
    ]
