# Generated by Django 2.1.6 on 2019-04-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_groups', '0003_auto_20190413_1539'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='interestgroup',
            options={'ordering': ['name', 'description']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name', 'registration_date']},
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='likes',
        ),
        migrations.AddField(
            model_name='grouppost',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to='interest_groups.Profile'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
