# Generated by Django 2.1.6 on 2019-04-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_groups', '0004_auto_20190413_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestgroup',
            name='thumbnail',
            field=models.ImageField(default='images/groups/thumbnails/default_thumbnail.jpg', upload_to='images/groups/thumbnails'),
        ),
    ]
