# Generated by Django 2.1.5 on 2019-04-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest_groups', '0004_auto_20190414_2108'),
        ('interest_groups', '0005_auto_20190414_0043'),
    ]

    operations = [
    ]
