# Generated by Django 2.1.5 on 2019-04-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest_groups', '0006_merge_20190415_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tagline',
        ),
    ]
