# Generated by Django 2.1.5 on 2019-04-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_groups', '0007_remove_profile_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phonenumber',
            field=models.CharField(default=0, max_length=20, verbose_name='Phone Number'),
        ),
    ]
