# Generated by Django 2.1.6 on 2019-04-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_groups', '0009_auto_20190428_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='/static/images/profile_pictures/default_profile_picture.png', upload_to='images/profile_pictures/'),
        ),
    ]
