# Generated by Django 2.1.5 on 2019-04-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest_groups', '0009_auto_20190428_1341'),
        ('interest_groups', '0010_auto_20190429_1458'),
    ]

    operations = [
    ]
