# Generated by Django 2.1.5 on 2019-04-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_groups', '0011_merge_20190429_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='/static/images/profile_pictures/default_profile_picture.png', upload_to='images/profile_pictures/'),
        ),
    ]
